name: CI (build)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup secrets
        env:
          FILE: ${{ secrets.SECRETS_TS }}
        run: echo $FILE > src/secrets.ts

      - name: yarn install, build typescript
        run: |
          yarn install
          yarn build
