name: CI (test)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup Oracle instant client
        run: |
          wget https://students.mimuw.edu.pl/~kw438800/instantclient.rpm
          sudo apt install alien libaio1
          sudo alien -i instantclient.rpm
          sqlplus

      - name: Setup secrets
        env:
          FILE: ${{ secrets.SECRETS_TS }}
        run: |
          echo $FILE > src/secrets.ts

      - name: Start server
        run: |
          yarn install
          yarn start &
          sleep 10
          yarn test
      - name: Upload coverage reports to Codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        uses: codecov/codecov-action@v3
