# This is a basic workflow to help you get started with Actions

name: CI (test)

# Controls when the workflow will run
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: add firebase service account json file
        env:
          JSON: ${{ secrets.FIREBASE_SERVICEACCOUNTJSON }}
        run: echo $JSON > src/serviceAccount.json

      # Runs a set of commands using the runners shell
      - name: Start server
        run: |
          yarn install
          yarn test
      - name: Upload coverage reports to Codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        uses: codecov/codecov-action@v3
