name: CI (test)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup secrets
        env:
          USER: ${{ secrets.KWASOW_USERNAME }}
          PASSWORD: ${{ secrets.KWASOW_PASSWORD }}
        run: |
          echo "export const user = '$USER';export const password = '$PASSWORD';" > src/secrets.ts

      - name: Setup SSH tunnel
        env:
          USER: ${{ secrets.KWASOW_USERNAME }}
          PASSWORD: ${{ secrets.KWASOW_PASSWORD }}
        run: |
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
          ssh -fN -L 5432:lkdb:5432 $USER:$PASSWORD@students.mimuw.edu.pl

      - name: Start server
        run: |
          yarn install
          yarn start &
          sleep 10
          yarn test
      - name: Upload coverage reports to Codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        uses: codecov/codecov-action@v3
